Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -65,6 +65,30 @@ jobs:
           echo "no" | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/avdmanager create avd -n TestEmulator -k "system-images;android-30;google_apis;x86_64" --force
           nohup /usr/local/lib/android/sdk/emulator/emulator -avd TestEmulator -no-audio -no-window &
 
+      - name: Wait for emulator to boot
+        run: |
+          adb wait-for-device
+          echo "Device detected. Waiting for it to boot..."
+          boot_completed=false
+          max_attempts=60  # Tempo máximo de espera: 5 minutos
+          attempts=0
+          while [ "$boot_completed" != "1" ] && [ $attempts -lt $max_attempts ]; do
+            sleep 5
+            boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
+            echo "Attempt $((attempts + 1)): boot_completed=$boot_completed"
+            adb shell getprop ro.build.version.release
+            adb shell getprop ro.product.model
+            adb devices
+            attempts=$((attempts + 1))
+          done
+          if [ "$boot_completed" != "1" ]; then
+            echo "Emulator failed to boot within the timeout period. Debug info:"
+            adb shell getprop
+            adb devices
+            exit 1
+          fi
+          echo "Emulator booted successfully!"
+
 
       - name: Run tests
         run: npx wdio local-wdio.conf.js # Substitua com o comando para rodar seus testes
